# Generated by Django 4.1.13 on 2024-03-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
