# Generated by Django 4.1.13 on 2024-03-07 07:28

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_alter_type_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='type',
            field=djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.type'),
        ),
    ]
