# Generated by Django 4.1.13 on 2024-02-22 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_items',
        ),
    ]
