# Generated by Django 4.1.13 on 2024-02-22 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_author_description_alter_category_description_and_more'),
        ('cart', '0002_alter_cartitem_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='book_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
