# Generated by Django 4.1.13 on 2024-03-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_book_id_cartitem_product_id_cartitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='user_id',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
