# Generated by Django 4.1.13 on 2024-03-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_normal_user',
            field=models.BooleanField(default=True),
        ),
    ]
